name: 'Tests'

on:
  push:
    branches:
      - v3
  pull_request:
  schedule:
    - cron: '30 8 * * 1'

jobs:
  tests:
    name: 'Tests'
    strategy:
      matrix:
        include:
          - php: '8.3.0'
            os: 'ubuntu-22.04'
            werror: 1
            xdebug: '3.3.0alpha3'

          - php: '8.2.0'
            os: 'ubuntu-22.04'
            werror: 1
            xdebug: '3.2.2'

          - php: '8.1.0'
            os: 'ubuntu-20.04'
            expect_native: 1
            werror: 1
            xdebug: '3.1.2'

          - php: '8.1.0'
            os: 'macos-13'
            xdebug: '3.1.2'

          - php: '8.0.0'
            os: 'ubuntu-20.04'
            expect_native: 1
            xdebug: '3.1.2'

          - php: '7.4.0'
            os: 'ubuntu-20.04'
            expect_native: 1
            xdebug: '3.1.2'

          - php: '7.3.0'
            os: 'ubuntu-20.04'
            expect_native: 1
            xdebug: '3.1.2'

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ !!matrix.experimental }}
    env:
      PHP_VERSION: ${{ matrix.php }}
      PHP_TAG: ${{ matrix.tag }}
      MEMORY_CHECK: ${{ matrix.memcheck }}
      WERROR: ${{ matrix.werror }}
      MEMPROF_EXPECT_NATIVE_TRACKING: ${{ matrix.expect_native }}
      XDEBUG_VERSION: ${{ matrix.xdebug }}
    steps:
      - name: 'Check out repository'
        uses: 'actions/checkout@v4'
        with:
          path: 'ext'

      - uses: 'actions/cache@v3'
        with:
          path: '~/build-cache/php'
          key: ${{ runner.os }}-${{ matrix.php }}-${{ matrix.memcheck }}

      - name: 'Build PHP'
        run: './ext/.github/workflows/test/build-php.sh'

      - name: 'Install xdebug'
        run: './ext/.github/workflows/test/build-xdebug.sh'

      - name: 'Build extension'
        run: './ext/.github/workflows/test/build-extension.sh'

      - name: 'Run tests'
        run: './ext/.github/workflows/test/tests.sh'
